# This file intentionally left blank
SERIAL_DRIVER = vendor
SPLIT_KEYBOARD = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
# OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes
# WS2812_DRIVER = vendor

OPT_DEFS += -DHAL_USE_I2C=TRUE

# ENCODER_ENABLE = yes
# ENCODER_MAP_ENABLE = yes